### ISSUE TITLE
Did you ever get this working?

### ISSUE THREAD

**Issue by git3rdone** [arojunior/handle-failed-requests-js#1]
I downloaded and used it but it's doing the same thing as the forked version. Did you ever get this working? It's a perfect solution for my situation.
Thanks!

**Comment by arojunior** [comment]
Hi @git3rdone , thanks for your feedback. Yes, I have this lib working in production.

I will take a look and make more tests, but it has a long time that I don't change anything here.

**Comment by arojunior** [comment]
Just made some tests and found a bug. It was not sending all failing requests when connection is back to up, probably because of localStorage async issues. But if you refresh the page, the missing requests are send.

I put a trigger to verify the failed requests when connection is back, can you test with this branch?

https://github.com/arojunior/handle-failed-requests-js/tree/fix-missing-requests

**Comment by git3rdone** [comment]
I will give it a go tomorrow. Thanks

On Apr 25, 2018 7:15 PM, "Junior Oliveira" <notifications@github.com> wrote:

Just made some tests and found a bug. It was not sending all failing
requests when connection is back to up, probably because of localStorage
async issues. But if you refresh the page, the missing requests are send.

I put a trigger to verify the failed requests when connection is back, can
you test with this branch?

https://github.com/arojunior/handle-failed-requests-js/tree/fix-missing-requests

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arojunior/handle-failed-requests-js/issues/1#issuecomment-384463053>,
or mute the thread

**Comment by git3rdone** [comment]
It does the opposite now and only sends the first result

**Comment by git3rdone** [comment]
Ill try to record it like that tomorrow.

On Apr 26, 2018 7:19 PM, "Junior Oliveira" <notifications@github.com> wrote:

How are you testing?

[image: handle-failed-requests]
<https://user-images.githubusercontent.com/7604033/39336674-19212d44-498f-11e8-9239-5bdc0710be2f.gif>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arojunior/handle-failed-requests-js/issues/1#issuecomment-384817591>,
or mute the thread

**Comment by git3rdone** [comment]
On Apr 26, 2018 7:19 PM, "Junior Oliveira" <notifications@github.com> wrote:

How are you testing?

[image: handle-failed-requests]
<https://user-images.githubusercontent.com/7604033/39336674-19212d44-498f-11e8-9239-5bdc0710be2f.gif>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arojunior/handle-failed-requests-js/issues/1#issuecomment-384817591>,
or mute the thread

**Comment by git3rdone** [comment]
Were you able to see that gif? I can send it another way. How did you
record yours?

On Apr 28, 2018 10:48 AM, "Junior Oliveira" <notifications@github.com>
wrote:

Closed #1 <https://github.com/arojunior/handle-failed-requests-js/issues/1>
via #2 <https://github.com/arojunior/handle-failed-requests-js/pull/2>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arojunior/handle-failed-requests-js/issues/1#event-1600153890>,
or mute the thread

**Comment by arojunior** [comment]
I recorded my screen with quicktime and then converted to gif. I will reopen this issue and give you some time to send more information to how to reproduce this bug.

**Comment by git3rdone** [comment]
can you see this one?




On Apr 30, 2018 8:44 PM, "Junior Oliveira" <notifications@github.com> wrote:

Reopened #1
<https://github.com/arojunior/handle-failed-requests-js/issues/1>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/arojunior/handle-failed-requests-js/issues/1#event-1602700054>,
or mute the thread

**Comment by arojunior** [comment]
![captura de tela 2018-05-01 as 11 23 48](https://user-images.githubusercontent.com/7604033/39476432-45371d3e-4d32-11e8-8abd-77bc5d53bf41.png)

Sorry, Dude. But there's nothing here. Are you sending by e-mail? I think you need to upload directly on Github.

**Comment by git3rdone** [comment]
Ya, I was emailing.. Trying to post

![onlysending1](https://user-images.githubusercontent.com/38736787/39476581-6c3695ca-4d2a-11e8-927c-5927e3f76a76.gif)

**Comment by arojunior** [comment]
Ok, now I can see that. Let's do some verifications:

1 - make sure that you are using the last version: https://github.com/arojunior/handle-failed-requests-js/blob/master/lib/handle-requests.min.js
2 - force your browser to cleanup the cache to ensure that you are really using the last downloaded version
3 - test again
4 - in case of things still not working well, check if your failed requests are persisted on localStorage:
![captura de tela 2018-05-01 as 12 58 24](https://user-images.githubusercontent.com/7604033/39480802-b7f0c782-4d3f-11e8-9e5c-b17bf95ca492.png)
All failed requests are persisted on localStorage and then removed when connection come back to normal

**Comment by git3rdone** [comment]
Ok, I did all that. I put a comment in your file just to be sure it changed, forced the update and tested with the same results.
There is nothing in local storage - I believe that is used for strings key/values only and I'm using custom objects

**Comment by arojunior** [comment]
Can you send to me an example of the payload? Then I can reproduce here.

**Comment by git3rdone** [comment]
Here's the raw form data:
id=307045&Passed=2&range_307045=2&comment=an+offline+comment&X-Requested-With=XMLHttpRequest

If you'd like to reproduce the environment, I'm using MVC and Ajax.BeginForm for submissions.
https://www.c-sharpcorner.com/UploadFile/0c1bb2/ajax-beginform-in-Asp-Net-mvc-5/

**Comment by git3rdone** [comment]
Were you able to reproduce the same results?

**Comment by arojunior** [comment]
Yes, now I figured why you are getting the same error as the Offline.js
To my implementation work correctly, you should create an instance of the `Request` class and use the `send()`method, as I mentioned in the Readme.

```javascript
var req = new Request();

req.send({
    method: 'post',
    data: { id: 1 },
    url: '/'
  })
  .then(function(res) {
    console.log(res);
  });
```

If you just import the file, you take only the Offline.js implementation. When you use the `send()` method from `Request` class, all failed requests are persisted on localStorage.

**Comment by git3rdone** [comment]
Oh, ok. You should take the 'no configuration' line under features off the front page. I read that and thought it was the same as offline.

**Comment by arojunior** [comment]
Yes, you're right. I'm sorry about that. It is because I don't take it as a configuration, but if you thought, it is because the documentation is not good enough.

Can I help you with something else?

**Comment by git3rdone** [comment]
Yes :) I have 72 different submit buttons that are dynamically created. What would be your recommendation for an offline strategy? I can't hard-code the req.send since I don't know what the data or url will be. Should I dynamically make 72 req.sends?

**Comment by arojunior** [comment]
Maybe. Do you have access to a `catch` action (to handle failed ajax request)? If you do, you can use the `queueFailedRequests` method from the lib.
I think it's the `OnFailure` callback from the lib that you are using... 
The `queueFailedRequests` takes the `data` as argument and then put on the queue list.
